{% set name = "f2c" %}
{% set version = "20160101" %}
{% set sha256 = "5e4e684faccda6bf15b8282766c7c9a21498498b1769652151bee151c9b212da" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jasercion/fermi-f2c/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [vc<14 and win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - unzip  # [not win]
  run:

test:
  commands:
    - test -f ${PREFIX}/include/f2c/f2c.h  # [not win]
    - conda inspect linkages -p $PREFIX f2c  # [not win]
    - conda inspect objects -p $PREFIX f2c  # [osx]
    - f2c --version
    - f2c test_main.f && ${CC} test_main.c -L${PREFIX}/lib -lf2c -I${PREFIX}/include -o test_main && ./test_main  # [not win]
  requires:
    - toolchain
  files:
    - test_main.f

about:
  home: http://www.netlib.org/f2c/
  license: OTHER
  license_family: OTHER
  license_file: permission
  summary: 'f2c is a program to convert Fortran 77 to C code, developed at Bell Laboratories.'
  description:  The standalone f2c program was based on the core of the first complete Fortran 77
                compiler to be implemented, the "f77" program by Feldman and Weinberger.
  doc_url: http://www.netlib.org/f2c/README
  dev_url: http://www.netlib.org/f2c/

extra:
  recipe-maintainers:
    - giacomov
    - jasercion
    - Areustle
