{% set name = "f2c" %}
{% set version = "20160102" %}
{% set sha256 = "fc287517edc67c184bf91860aaa7b342c6c8ce008b298c2a08c4616133009c21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar
  url: http://netlib.sandia.gov/cgi-bin/netlib/netlibfiles.tar?filename=netlib/{{name}}
  sha256: {{ sha256 }}
  patches:
    - freebsd-86884.patch  # [win]

build:
  number: 2
  features:
    - vc14  # [win]
  msvc_compiler: 14.0

requirements:
  build:
    - vc 14  # [win]
    - toolchain
    - unzip  # [not win]
  run:
    - vc 14  # [win]

test:
  commands:
    - test -f ${PREFIX}/include/f2c/f2c.h  # [not win]
    - conda inspect linkages -p $PREFIX f2c  # [not win]
    - conda inspect objects -p $PREFIX f2c  # [osx]
    - f2c --version
    - f2c test_main.f && ${CC} test_main.c -L${PREFIX}/lib -lf2c -I${PREFIX}/include -o test_main && ./test_main  # [not win]
  requires:
    - toolchain
  files:
    - test_main.f

about:
  home: http://www.netlib.org/f2c/
  license: OTHER
  license_family: OTHER
  license_file: permission
  summary: 'f2c is a program to convert Fortran 77 to C code, developed at Bell Laboratories.'
  description:  The standalone f2c program was based on the core of the first complete Fortran 77 
                compiler to be implemented, the "f77" program by Feldman and Weinberger.
  doc_url: http://www.netlib.org/f2c/README
  dev_url: http://www.netlib.org/f2c/

extra:
  recipe-maintainers:
    - giacomov
