compiler_stack: comp7
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
max_py_ver: '37'
max_r_ver: '35'
provider:
  linux_aarch64: default
  linux_ppc64le: default
